// packages/solid/src/factory/variants.ts
import { mergeProps } from 'solid-js'
import type { JSX } from 'solid-js'
import type {
  CmBaseComponent,
  InputComponent,
  LogicHandler,
  MergeProps,
  StyleDefinition,
  VariantsConfig,
} from '../types'
import createSolidElement from '../util/createSolidElement'

interface CreateVariantsOptions<T extends object> {
  logic?: LogicHandler<T>[]
}

/**
 * Creates a Solid component with variant-based class names and styles.
 */
const createVariantsComponent = <
  E extends keyof JSX.IntrinsicElements | InputComponent,
  ExtraProps extends object,
  VariantProps extends object,
>(
  tag: E,
  config: VariantsConfig<VariantProps, ExtraProps>,
  options: CreateVariantsOptions<MergeProps<E, ExtraProps & Partial<VariantProps>>> = {},
): CmBaseComponent<MergeProps<E, ExtraProps & Partial<VariantProps>>> => {
  const { base, variants, defaultVariants = {} } = config
  const propsToFilter = Object.keys(variants)
  const styles: Record<string, string | number> = {}
  const displayName = `Variants(${typeof tag === 'string' ? tag : 'Component'})`
  const logicHandlers = options.logic ?? []

  const computeClassName = (
    props: MergeProps<E, Partial<VariantProps> & ExtraProps>,
    collectedStyles: Record<string, string | number>,
  ) => {
    const styleUtility = (styleDef: StyleDefinition<MergeProps<E, Partial<VariantProps> & ExtraProps>>) => {
      Object.assign(collectedStyles, styleDef)
      return ''
    }

    type InterpolationProps = MergeProps<E, Partial<VariantProps> & ExtraProps> & {
      style: typeof styleUtility
    }
    let interpolationProps: InterpolationProps | undefined
    const getInterpolationProps = () => {
      if (!interpolationProps) {
        interpolationProps = mergeProps(props, { style: styleUtility }) as InterpolationProps
      }
      return interpolationProps
    }

    // base classes and styles
    const interpolationTarget = getInterpolationProps() as VariantProps & ExtraProps & { style: typeof styleUtility }
    const baseClasses = typeof base === 'function' ? base(interpolationTarget) : base || ''

    // variant classes and styles
    const variantClasses = Object.entries(variants).map(([key, variantOptions]) => {
      const propValue = props[key] ?? (defaultVariants as Record<string, string | number | boolean | undefined>)[key]
      const hasValue = propValue !== undefined && propValue !== null
      const variantClass = hasValue ? (variantOptions as Record<string, any>)?.[String(propValue)] : undefined

      if (typeof variantClass === 'function') {
        return variantClass(interpolationTarget)
      }
      return variantClass || ''
    })

    return [baseClasses, ...variantClasses].filter(Boolean).join(' ').trim().replace(/\s+/g, ' ').trim()
  }

  return createSolidElement({
    tag,
    computeClassName: (props) => computeClassName(props, styles),
    displayName,
    styles,
    propsToFilter,
    logicHandlers,
  }) as CmBaseComponent<MergeProps<E, Partial<VariantProps> & ExtraProps>>
}

export default createVariantsComponent

// packages/react/src/factory/variants.ts
import type { JSX } from 'react'
import type {
  CmBaseComponent,
  InputComponent,
  LogicHandler,
  MergeProps,
  StyleDefinition,
  VariantsConfig,
} from '../types'
import createReactElement from '../util/createReactElement'

interface CreateVariantsOptions<T extends object> {
  logic?: LogicHandler<T>[]
}

/**
 * Creates a React component with variant-based class names and styles.
 *
 * @template E - The type of the element or component.
 * @template ExtraProps - Additional props for the component.
 * @template VariantProps - Props for the variants.
 *
 * @param {E} tag - The HTML tag or React component.
 * @param {VariantsConfig<VariantProps, ExtraProps>} config - Configuration for the variants.
 * @returns {CmBaseComponent<MergeProps<E, ExtraProps & Partial<VariantProps>>>} - The created React component.
 */
const createVariantsComponent = <
  E extends keyof JSX.IntrinsicElements | InputComponent,
  ExtraProps extends object,
  VariantProps extends object,
>(
  tag: E,
  config: VariantsConfig<VariantProps, ExtraProps>,
  options: CreateVariantsOptions<MergeProps<E, ExtraProps & Partial<VariantProps>>> = {},
): CmBaseComponent<MergeProps<E, ExtraProps & Partial<VariantProps>>> => {
  const { base, variants, defaultVariants = {} } = config
  const propsToFilter = Object.keys(variants)
  const styles: Record<string, string | number> = {}
  const displayName = `Variants(${typeof tag === 'string' ? tag : 'Component'})`
  const logicHandlers = options.logic ?? []

  const computeClassName = (
    props: MergeProps<E, Partial<VariantProps> & ExtraProps>,
    collectedStyles: Record<string, string | number>,
  ) => {
    const styleUtility = (styleDef: StyleDefinition<MergeProps<E, Partial<VariantProps> & ExtraProps>>) => {
      Object.assign(collectedStyles, styleDef)
      return ''
    }

    // base classes and styles
    const baseClasses = typeof base === 'function' ? base({ ...props, style: styleUtility }) : base || ''

    // variant classes and styles
    const variantClasses = Object.entries(variants).map(([key, variantOptions]) => {
      const propValue = props[key] ?? (defaultVariants as Record<string, string | number | boolean | undefined>)[key]
      const hasValue = propValue !== undefined && propValue !== null
      const variantClass = hasValue ? (variantOptions as Record<string, any>)?.[String(propValue)] : undefined

      if (typeof variantClass === 'function') {
        return variantClass({ ...props, style: styleUtility })
      }
      return variantClass || ''
    })

    return [baseClasses, ...variantClasses].filter(Boolean).join(' ').trim().replace(/\s+/g, ' ').trim()
  }

  return createReactElement({
    tag,
    computeClassName: (props) => computeClassName(props, styles),
    displayName,
    styles,
    propsToFilter,
    logicHandlers,
  }) as CmBaseComponent<MergeProps<E, Partial<VariantProps> & ExtraProps>>
}

export default createVariantsComponent
